# -*- coding: utf-8 -*-
"""Natural Language Processing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1F48oyRwF3tQlIB04PzzQAl2T5Qy8U6KD

To translate each word or sentence from English to Spanish, French and German
"""

pip install googletrans==3.1.0a0

from googletrans import Translator
import numpy as np 
import pandas as pd

translator = Translator()

df = pd.read_csv('/content/English.csv')
df

df['Spanish'] = df['English words/sentences'].apply(translator.translate, dest='es').apply(getattr, args=('text',))
df['French'] = df['English words/sentences'].apply(translator.translate, dest='fr').apply(getattr, args=('text',))
df['German'] = df['English words/sentences'].apply(translator.translate, dest='de').apply(getattr, args=('text',))

df

"""Create a program that needs to automatically correct that spelling from the word or a given sentence. (Language : English) 

"""

pip install autocorrect

from autocorrect import spell

import numpy as np 
import pandas as pd

df = pd.read_csv('/content/English.csv')
df

df['English words/sentences'].apply(lambda x: " ".join([spell(i) for i in x.split()]))

df.head(100)

"""Create an application that should be used by the HR Team to filter the resume based on the Skills.

"""

def cleanResume(sentence):
    sentence = re.sub('httpS+s*', ' ', resumeText)  # remove URLs
    sentence = re.sub('RT|cc', ' ', resumeText)  # remove RT and cc
    sentence = re.sub('#S+', '', resumeText)  # remove hashtags
    sentence= re.sub('@S+', '  ', resumeText)  # remove mentions
    sentence = re.sub('[%s]' % re.escape("""!"#$%&'()*+,-./:;<=>?@[]^_`{|}~"""), ' ', resumeText)  # remove punctuations
    sentence = re.sub(r'[^x00-x7f]',r' ', resumeText) 
    sentence = re.sub('s+', ' ', resumeText)  # remove extra whitespace
    return sentence
sentence['cleaned_resume'] = sentence.Resume.apply(lambda x: cleanResume(x))

"""Create a chatbot for Hotel Management to Book Rooms """

!pip install chatterbot
from chatterbot import ChatBot

from chatterbot.trainers import ChatterBotCorpusTrainer

chatbot=ChatBot('Book Rooms')

trainer = ChatterBotCorpusTrainer(chatbot)

trainer.train("chatterbot.corpus.english.greetings",
              "chatterbot.corpus.english.conversations" )

response = chatbot.get_response('Customer Name')
print(response)

response = chatbot.get_response('Address')
print(response)

response = chatbot.get_response('Mobile Number')
print(response)

response = chatbot.get_response('ID proof')
print(response)

response = chatbot.get_response('Room Type')
print(response)

response = chatbot.get_response('date of arrival')
print(response)

response = chatbot.get_response('departure date')
print(response)